### ISSUE TITLE
can i batch generate private keys with compressed and uncompressed

### ISSUE THREAD

**Issue by pacnload** [vsergeev/btckeygenie#10]
hey sergee i am working on a btc puzzle chalenge and i need to generate privat keys in hex

start:
0000000000000000000000000000000000000000000000007cce5efdaccf6808
ending: 
000000000000000000000000000000000000000000000001a838b13505b26867

is there any way to generate private keys from them with compressed and uncompressed format and exporting them to 100MB splitted files?
i think your code is like this but i dont know how can i generated it counting 1 by 1 line and not random

**Comment by vsergeev** [comment]
I'm afraid I might not fully understand your question. If the start and end byte strings you provided are private keys and you just want to derive all the compressed and uncompressed public keys from them, then you could do it like this:

``` go

package main

import (
	"fmt"
	"github.com/vsergeev/btckeygenie/btckey"
	"math/big"
)

func main() {
	start_prikey, _ := new(big.Int).SetString("0000000000000000000000000000000000000000000000007cce5efdaccf6808", 16)
	end_prikey, _ := new(big.Int).SetString("000000000000000000000000000000000000000000000001a838b13505b26867", 16)
	one := big.NewInt(1)

	for prikey := start_prikey; prikey.Cmp(end_prikey) <= 0; prikey = prikey.Add(prikey, one) {
		priv := btckey.NewPrivateKey(prikey)
		fmt.Printf("%x %x\n", priv.PublicKey.ToBytes(), priv.PublicKey.ToBytesUncompressed())
	}
}
```

```
0365ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a54579 0465ec2994b8cc0a20d40dd69edfe55ca32a54bcbbaa6b0ddcff36049301a545795a1b76ab01e9edd0de24157ceff77bcb0f615560b250b365a5d435873eaa4625
03d6b602d53fa21fb95454006b4a55bf34c6785415c74dae9fdfd2affa96f7d37c 04d6b602d53fa21fb95454006b4a55bf34c6785415c74dae9fdfd2affa96f7d37ca5b124835c95cdbaf0e97ee52e86f02b22fee05b5fa1884dabc6208e4b118c35
03d2942ada8906251a2e8696a8342cd9fd9a817dbaf8977a668b91e5fec48a7aa0 04d2942ada8906251a2e8696a8342cd9fd9a817dbaf8977a668b91e5fec48a7aa0df951c9dfecec921afb894df5c1f4d4a573b0a77483c36726902298ed453581f
02ff47471b0df183752a8e3ddeac1b887fca6feec1ca10322297c2a30211f39da6 04ff47471b0df183752a8e3ddeac1b887fca6feec1ca10322297c2a30211f39da6a6f24ad90e2207531102de3c38d7caa4e2799d25ed9f05dc3d6b0c98f5cb457c
024f58c62df3c21839951fd059a45cbe9626f879aebb381a667b88d5802cfd3ec3 044f58c62df3c21839951fd059a45cbe9626f879aebb381a667b88d5802cfd3ec3d6da3c4a6011c32aab4949c8fca305407763ce4e766c7077118da68d998a208e
...
```

First column is compressed public key bytes and second column is uncompressed public key bytes. You can use the `priv.ToAddress()` and `priv.ToAddressUncompressed()` to compute the Base58 addresses as well. See the btckeygenie [top-level](https://github.com/vsergeev/btckeygenie/blob/master/main.go) to see how other address formats are printed.

**Comment by musamiyas** [comment]
Good evening
Please do you have some way to generate oly the ECDSA public keys from the private keys in sequence using this library "github.com/ethereum/go-ethereum/crypto/secp256k1"
