### ISSUE TITLE
bulk

### ISSUE THREAD

**Issue by marissia** [vsergeev/btckeygenie#11]
can I generate mass addresses from wif file ? if i have about 1 million wif keys? how I can do it ? as I see till now inly by one key possible, please help!

**Comment by vsergeev** [comment]
Just modify `https://github.com/vsergeev/btckeygenie/blob/master/main.go` to open your files in a loop and dump the address you need.

**Comment by marissia** [comment]
простите а можно подробнее,что именно поменятьв  в файле? для слабых умов я не программист. по инструкции запустила через командную строку и больше ничего не могу, что на что изменить и какая команда в консоли чтоб вывести -o и -i ? спасибо за быстрый ответ

**Comment by marissia** [comment]
what I will modify please help!!

**Comment by vsergeev** [comment]
Вы можите запустить btckeygenie за каждый WIF в файле через командную строку:

```
$ cat wifs.txt
L3qctLdwyKffwqRFRw9njXbwSjhAnn69BYfUQ5vvKvs3p9faxtbX
Kz1BAzYjDxQaBAzxivsuY39SYbgkXKXm1bXQYQjvnwNan7bbbqV6
KyWcBeRKH47whZPYRcheiLstTPc2bGbe9FZb4ERosJuoHtuCgRno
...
$ for wif in $(cat wifs.txt); do ./btckeygenie $wif | grep "Bitcoin Address"; done
Bitcoin Address (Compressed)        16Be3sWFptypta3uhuet4nuTQ9YGt55qVP
Bitcoin Address (Uncompressed)      1GeVUugfqPtt2FcL6N22Kz5A4vjvhBYAnr
Bitcoin Address (Compressed)        1CqmcCPt7rvNeKkLbe5MYnHFLqJ97qru2G
Bitcoin Address (Uncompressed)      1CU9ichUHQ2Sp9K3Mc1uSUwNzM4oeVCocf
Bitcoin Address (Compressed)        1By6d3BH1YjeqkC6z5X8bizNNCTPMFTmcQ
Bitcoin Address (Uncompressed)      13pcA44FnSrixZSiFsX62m3NGYpCDSnBiF
$
```

Чтобы вычислить быстрее требует модификации в программе, но это слишком сложно объяснить, если вы не программист ... Простите, мне просто не хватает времени.

**Comment by marissia** [comment]
ну спасибо огромное,вроде поняла ...))))

**Comment by marissia** [comment]
сорри я опять, вы можете мне написать готовую команду для Windows cmd? вот есть файл 3 миллиона ключей из них нужно получить адреса, в консоль столько не влезет, затормозит, команда читать из файла и сохранить в файл как закончит. ну и что в файле изменить перед этим? что то не получается. я не в Linux работаю . Помогите умоляю уже устала сама..

**Comment by vsergeev** [comment]
к сожалению, я недостаточно знаком с Windows cmd, чтобы дать вам аналогичные инструкции...

**Comment by marissia** [comment]
хорошо ну тогда команда точная в linux ?? что то нужно менять в фвйле main.go ??и вывод точный в терминал, я пыталась так cat wifs.txt но ничего не выходит и вообще говорит что формат base58 ошибка хотя там все ключи Wif / может что то в файле менять и надо вводить команду go run main,go ? пожалуйста напишите и я не буду больше доставать. сорри еще раз
